server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:"prod"}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/cardsdb}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root}
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/}
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

logging:
  level:
    com:
      cgnexus:
        cards: ${LOG_LEVEL_COM_CGNEXUS_ACCOUNTS:DEBUG}
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "cards"
    description: "Cards Microservice"
    version: "1.0.0"