server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:"prod"}
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/}
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

docker:
  username: ${DOCKER_USERNAME}
  password: ${DOCKER_PASSWORD}


management:
  endpoints:
    web:
      exposure:
        include: "*"