services:
  accounts:
    image: magises/accounts:section4
    container_name: accounts-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cgnexus-ms
    env_file:
      - .env
  cards:
    image: magises/cards:0.0.1-SNAPSHOT
    container_name: cards-ms
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cgnexus-ms
    env_file:
      - .env
  loans:
    image: magises/loans:0.0.1
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cgnexus-ms
    env_file:
      - .env
networks:
  cgnexus-ms:
    driver: bridge