spring:
  application:
    name: "gatewayserver"
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/}
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

logging:
  level:
    com:
      cgnexus:
        gatewayserver: DEBUG
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "CGNEXUS Gateway Server"
    version: "1.0.0"