server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:"prod"}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/loansdb}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root}
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/}
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
logging:
  level:
    com:
      eazybytes:
        loans: ${LOG_LEVEL_COM_CGNEXUS_ACCOUNTS:DEBUG}
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: "loans"
    description: "Loans Microservice"
    version: "1.0.0"