spring:
  application:
    name: "eurekaserver"
  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071/}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: ${SERVER_PORT:8070}
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:false} # this is false because this is the eureka server
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false} # this is false because this is the eureka server
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8070}/eureka/
