spring:
  application:
    name: accounts
server:
  port: 8082
logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
docker:
  username: ${DOCKER_USERNAME}
  password: ${DOCKER_PASSWORD}

build:
  version: "1.0.0"