services:
  configserver:
    image: magises/configserver:s6
    container_name: configserver-ms
    ports:
      - "8071:8071"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cgnexus-ms
    env_file:
      - .env

  accounts:
    image: magises/accounts:s6
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cgnexus-ms
    environment:
      - SPRING_APPLICATION_NAME:"accounts"
      - SPRING_CONFIG_IMPORT:"configserver:http://configserver:8071"
      - SPRING_PROFILES_ACTIVE:"default"
    env_file:
      - .env
  cards:
    image: magises/cards:s6
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cgnexus-ms
    environment:
      - SPRING_APPLICATION_NAME:"cards"
      - SPRING_CONFIG_IMPORT:"configserver:http://configserver:8071"
      - SPRING_PROFILES_ACTIVE:"default"
    env_file:
      - .env
  loans:
    image: magises/loans:s6
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cgnexus-ms
    environment:
      - SPRING_APPLICATION_NAME:loans"
      - SPRING_CONFIG_IMPORT:"configserver:http://configserver:8071"
      - SPRING_PROFILES_ACTIVE:"default"
    env_file:
      - .env
networks:
  cgnexus-ms:
    driver: bridge