services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - cgnexus-ms
    deploy:
      resources:
        limits:
          memory: 700m

  configserver:
    image: magises/configserver:s6
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail http://localhost:8071/actuator/health/readiness | grep UP || exit 1" # check if the server is up
      interval: 10s # check every 10 seconds
      timeout: 5s # wait 5 seconds before considering the check to have failed
      retries: 10 # retry 10 times before giving up
      start_period: 10s # wait for 10 seconds before running the first check
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cgnexus-ms
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy

  accounts:
    image: magises/accounts:s6
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cgnexus-ms
    environment:
      - SPRING_APPLICATION_NAME:"accounts"
      - SPRING_CONFIG_IMPORT:"configserver:http://configserver:8071"
      - SPRING_PROFILES_ACTIVE:"default"
    env_file:
      - .env
    depends_on:
      configserver:
        condition: service_healthy
  cards:
    image: magises/cards:s6
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cgnexus-ms
    environment:
      - SPRING_APPLICATION_NAME:"cards"
      - SPRING_CONFIG_IMPORT:"configserver:http://configserver:8071"
      - SPRING_PROFILES_ACTIVE:"default"
    env_file:
      - .env
    depends_on:
      configserver:
        condition: service_healthy
  loans:
    image: magises/loans:s6
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - cgnexus-ms
    environment:
      - SPRING_APPLICATION_NAME:loans"
      - SPRING_CONFIG_IMPORT:"configserver:http://configserver:8071"
      - SPRING_PROFILES_ACTIVE:"default"
    env_file:
      - .env
    depends_on:
      configserver:
        condition: service_healthy
networks:
  cgnexus-ms:
    driver: bridge